name: Backend - CI

on:
  pull_request:
    paths:
      - web/packages/backend/**
      - .github/workflows/backend-ci.yaml
  push:
    branches:
      - main
    paths:
      - web/packages/backend/**
      - .github/workflows/backend-ci.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web/packages/backend
    permissions:
      contents: read
    steps:
      - name: Check out codes
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun check

      - name: Build
        run: bun run build

      - name: Prepare Test
        run: |
          docker compose -f ../../../docker/docker-compose.yaml up -d
          bun test:init-db

      - name: Test
        run: bun test
